# Automatically created from terraform data on 

all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: rohit


zookeeper:
  hosts:
    ip-172-30-23-66.eu-west-1.compute.internal:
    ip-172-30-22-217.eu-west-1.compute.internal:
    ip-172-30-27-93.eu-west-1.compute.internal:
    
kafka_broker:
  hosts:
    ip-172-30-19-241.eu-west-1.compute.internal:
    ip-172-30-27-71.eu-west-1.compute.internal:
    ip-172-30-19-221.eu-west-1.compute.internal:
    ip-172-30-21-129.eu-west-1.compute.internal:
    

schema_registry:
  hosts:
    ip-172-30-23-4.eu-west-1.compute.internal:
    ip-172-30-28-145.eu-west-1.compute.internal:
    

kafka_rest:
  hosts:
    ip-172-30-30-59.eu-west-1.compute.internal:
    

ksql:
  hosts:
    ip-172-30-26-119.eu-west-1.compute.internal:
    ip-172-30-25-85.eu-west-1.compute.internal:
    

kafka_connect:
  hosts:
    ip-172-30-25-242.eu-west-1.compute.internal:
    ip-172-30-20-237.eu-west-1.compute.internal:
    

control_center:
  hosts:
    ip-172-30-30-186.eu-west-1.compute.internal:
    
